# Generated by Django 5.0.2 on 2024-02-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_encrypt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='encrypted_file',
            field=models.FileField(upload_to='encrypted_files/'),
        ),
    ]
