# Generated by Django 5.0.2 on 2024-02-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_encrypt', '0002_alter_encryptedfile_encrypted_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='encrypted_file',
            field=models.FileField(upload_to='encrypted_file/'),
        ),
    ]
