# Generated by Django 5.0.2 on 2024-02-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_encrypt', '0003_alter_encryptedfile_encrypted_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedfile',
            name='encrypted_file',
        ),
        migrations.RemoveField(
            model_name='encryptedfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='encryptedfile',
            name='id',
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='encrypted_content',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='file_id',
            field=models.AutoField(default=b'', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
